version: '3.8'

services:
  mosquitto-child1:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-child1
    ports:
      - "1884:1883"
    volumes:
      - ./config/mosquitto.config:/mosquitto/config/mosquitto.conf
      - shared-data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - mqtt-network
    restart: unless-stopped
    depends_on:
      - network-setup

  network-setup:
    image: busybox
    command: sh -c "exit 0"
    networks:
      - mqtt-network

volumes:
  shared-data:
    external: true
    name: mqtt-shared-data

networks:
  mqtt-network:
    external: true
    name: mqtt-bridge-network
